const COMMITS_MOCK = {
  head: 14,
  commits: [
    {
      id: 1,
      message: "Primeiro commit",
      createdAt: "2023-09-19T10:00:00",
      branchesId: ["branch1"],
      author: "Rafael Tsuha",
    },
    {
      id: 2,
      message: "Adicionado arquivo de configuração",
      createdAt: "2023-09-20T14:30:00",
      branchesId: ["branch1"],
      author: "Rafael Tsuha",
    },
    {
      id: 3,
      message: "Correções de bugs no arquivo principal",
      createdAt: "2023-09-21T09:15:00",
      branchesId: ["branch1"],
      author: "Rafael Tsuha",
    },
    {
      id: 4,
      message: "Adicionada funcionalidade de login",
      createdAt: "2023-09-22T16:45:00",
      branchesId: ["branch1"],
      author: "Rafael Tsuha",
    },
    {
      id: 5,
      message: "Correção de estilo no arquivo de configuração",
      createdAt: "2023-09-22T17:30:00",
      branchesId: ["branch1"],
      author: "Rafael Tsuha",
    },
    {
      id: 6,
      message: "Adicionada funcionalidade de carrinho de compras",
      createdAt: "2023-09-23T11:20:00",
      branchesId: ["branch1", "branch3"],
      author: "Rafael Tsuha",
    },
    {
      id: 7,
      message: "Primeiro commit da branch2",
      createdAt: "2023-09-20T11:00:00",
      branchesId: ["branch2"],
      author: "Rafael Tsuha",
    },
    {
      id: 8,
      message: "Correções na branch2",
      createdAt: "2023-09-21T14:45:00",
      branchesId: ["branch2"],
      author: "Rafael Tsuha",
    },
    {
      id: 9,
      message: "Funcionalidade adicional na branch2",
      createdAt: "2023-09-22T10:30:00",
      branchesId: ["branch2", "branch1"],
      author: "Rafael Tsuha",
    },
    {
      id: 10,
      message: "Primeiro commit da branch3",
      createdAt: "2023-09-23T09:30:00",
      branchesId: ["branch3"],
      author: "Rafael Tsuha",
    },
    {
      id: 11,
      message: "Adicionado arquivo de configuração na branch3",
      createdAt: "2023-09-23T14:00:00",
      branchesId: ["branch3"],
      author: "Zé",
    },
    {
      id: 12,
      message: "Correções na branch3",
      createdAt: "2023-09-24T11:15:00",
      branchesId: ["branch3"],
      author: "Rafael Tsuha",
    },
    {
      id: 13,
      message: "Funcionalidade de pagamento na branch3",
      createdAt: "2023-09-25T15:30:00",
      branchesId: ["branch3"],
      author: "Rafael Tsuha",
    },
    {
      id: 14,
      message: "Funcionalidade de envio na branch3",
      createdAt: "2023-09-26T16:45:00",
      branchesId: ["branch3"],
      author: "Rafael Tsuha",
    },
  ],
};

module.exports = {
  COMMITS_MOCK,
};
